project_id = "eclipsesystems-timekeeping"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://eclipsesystems.pro/auth/callback", "http://localhost:3000/auth/callback"]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
redirect_uri = ""

[auth.external.apple]
enabled = true
client_id = "env(SUPABASE_AUTH_APPLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_APPLE_SECRET)"
redirect_uri = ""

[auth.external.azure]
enabled = true
client_id = "env(SUPABASE_AUTH_AZURE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_AZURE_SECRET)"
url = "env(SUPABASE_AUTH_AZURE_URL)"
redirect_uri = ""

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = ""

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.invite-member]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = true
