type QuizQuestion = {
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

type LmsCourseSeed = {
  id: string;
  title: string;
  category: "safety" | "compliance" | "onboarding" | "software" | "soft skills";
  duration: string;
  description: string;
  lessons: Array<{ title: string; body: string }>;
  quiz: string;
  quizQuestions: QuizQuestion[];
};

function lesson(title: string, intro: string, points: string[], takeaway: string, note?: string) {
  return [
    note ? `**Training summary:** ${note}` : undefined,
    intro,
    "",
    "**Key practices:**",
    ...points.map((point) => `- ${point}`),
    "",
    `**Takeaway:** ${takeaway}`
  ].filter(Boolean).join("\n");
}

export const lmsCourseCatalog: LmsCourseSeed[] = [
  {
    id: "course-new-hire",
    title: "New Hire Orientation",
    category: "onboarding",
    duration: "45 min",
    description: "A first-week guide to Ridgeway expectations, team norms, safety culture, and where to find help.",
    lessons: [
      { title: "Company overview and values", body: lesson("Company overview and values", "Ridgeway’s work depends on reliability: showing up prepared, communicating early, and leaving every client site safer and cleaner than we found it. The company serves commercial facilities, schools, apartments, and local businesses that depend on us to keep buildings running. Your first week is about learning how your work connects to that promise.", ["Put safety before speed. A late job can be recovered; a preventable injury changes lives and damages trust.", "Communicate before surprises become problems. If you are delayed, missing parts, or unsure about scope, update dispatch or your manager while options still exist.", "Protect client confidence. Use respectful language, keep work areas orderly, and document what you found, what you changed, and what still needs attention.", "Ask questions early. New hires are expected to learn; guessing in the field creates rework and risk."], "Use the first week to learn the standard, not to prove you already know everything.") },
      { title: "Field safety culture", body: lesson("Field safety culture", "Field safety at Ridgeway is a shared habit, not a poster on a wall. Every technician, dispatcher, and manager is expected to stop work when conditions are unclear or unsafe. A good safety culture rewards the person who slows down to verify hazards before starting the task.", ["Perform a quick scene scan before work: traffic, weather, energized equipment, trip hazards, ladders, roof access, chemicals, and nearby people.", "Use the right PPE for the task and replace damaged gear. Safety glasses, gloves, hearing protection, and fall protection only help when they fit and are worn correctly.", "Report near misses without blame. Near misses show where the system needs attention before someone gets hurt.", "Do not bypass procedures to save time. Lockout/tagout, ladder setup, and refrigerant handling steps exist because shortcuts repeatedly caused injuries in the real world."], "If a setup feels wrong, pause and call. A short delay is better than a preventable incident.", "This is internal safety training summary material and does not replace OSHA-required training where that is required.") },
      { title: "Dispatch workflow", body: lesson("Dispatch workflow", "Dispatch is the coordination point between client expectations, technician availability, parts, and job documentation. The Operations Hub keeps everyone looking at the same work order, so the best thing you can do is update it as reality changes. A quiet ticket usually creates confusion.", ["Review the assignment before leaving: client name, site address, contact, priority, symptoms, access notes, and any previous ticket history.", "Update status when you are en route, on site, waiting on client, waiting on parts, or complete. Status changes help dispatch answer client questions without interrupting you.", "Add clear notes: what you observed, readings or photos that matter, temporary fixes, parts needed, and next recommended step.", "Escalate quickly when scope changes. If you discover after-hours work, quote-level repairs, safety concerns, or client dissatisfaction, bring in the manager before committing."], "Good dispatch workflow means the next person can understand the job without calling you for basic context.") },
      { title: "Paperwork basics", body: lesson("Paperwork basics", "Paperwork is part of the job because it turns field work into payroll, billing, compliance records, and client trust. Incomplete notes delay invoices, make callbacks harder, and can cause pay or approval questions later. The goal is not long writing; it is complete, factual writing.", ["Clock in and out accurately. If you miss a punch, submit a correction with the reason as soon as possible instead of waiting for payroll review.", "Use job notes to separate facts from recommendations. “Compressor shorted to ground” is a fact; “recommend replacement quote” is the next step.", "Attach photos when they clarify condition, access, model/serial numbers, or completed work. Avoid photos of unrelated people or private client information.", "Complete required forms before leaving the site when possible: signatures, checklists, refrigerant logs, and safety observations are harder to reconstruct later."], "Write notes for the person who was not there: specific, factual, and complete enough to act on.") },
      { title: "Quiz: first week scenarios", body: lesson("Quiz: first week scenarios", "The first-week quiz checks whether you can apply orientation basics to common situations: delays, safety concerns, paperwork, and client communication. Read each prompt as if it happened on a real service day and choose the response that protects safety and keeps the team informed.", ["Look for the action that communicates early, documents clearly, and avoids guessing.", "Do not choose an answer that hides a problem, skips a safety step, or waits until the end of the day to report an issue.", "For client-facing situations, choose language that is factual and respectful without promising work outside your authority.", "When in doubt, involve dispatch or your manager before making commitments that affect schedule, price, or safety."], "The right answer usually keeps the shared record accurate and brings the right person into the loop.") }
    ],
    quiz: "Quiz: first week scenarios",
    quizQuestions: [
      { prompt: "You discover unsafe roof access at a client site. What should you do first?", options: ["Continue carefully to avoid delaying the job", "Stop, document the concern, and contact dispatch or a manager", "Ask the client to hold the ladder while you climb", "Skip notes and mention it at the end of the week"], correctIndex: 1, explanation: "Unsafe access should stop work until the hazard is reviewed and documented." },
      { prompt: "Which note best supports billing and follow-up?", options: ["Fixed unit", "Client seemed happy", "Found failed contactor, replaced part, verified cooling at 52°F supply air", "Need to come back sometime"], correctIndex: 2, explanation: "Specific findings, actions, and verification make the record useful." },
      { prompt: "If you are running late to the next call, the best response is to:", options: ["Wait until the client calls", "Update dispatch as soon as you know", "Mark the job complete", "Ask another technician to cover without telling dispatch"], correctIndex: 1, explanation: "Early updates let dispatch reset expectations and protect the schedule." }
    ]
  },
  {
    id: "course-time",
    title: "Time & Attendance Policy",
    category: "onboarding",
    duration: "20 min",
    description: "How hourly staff clock in, correct missed punches, read pay periods, and avoid payroll delays.",
    lessons: [
      { title: "Clock-in rules", body: lesson("Clock-in rules", "Accurate clocking protects payroll, job costing, and compliance. Clock in when you are beginning paid work and clock out when paid work ends. Do not clock in for another employee, allow someone else to clock for you, or leave a shift running after work has stopped.", ["Use the Operations Hub timekeeping page at the start of the shift, before beginning job duties or travel that is considered paid time.", "Confirm the correct day, site, and job context when prompted. Wrong job coding makes invoices and labor reports harder to trust.", "Do not adjust time casually. If something is wrong, use the correction request so the change is visible and approved.", "If the app or connection fails, notify your manager and submit the missing punch as soon as possible with a clear note."], "Clock events should describe what actually happened, not what you meant to enter later.") },
      { title: "Breaks and travel time", body: lesson("Breaks and travel time", "Break and travel rules affect both pay and job costing, so they must be recorded consistently. Follow the local policy your manager gives you for meal periods, rest breaks, and paid travel. When you are unsure whether time is paid, ask before making assumptions.", ["Start and end unpaid meal breaks according to policy. A forgotten break entry should be corrected the same day when possible.", "Keep travel time tied to the correct job or shift context. Dispatch uses that information to understand route efficiency and schedule realism.", "Do not work through an unpaid break unless a manager has approved the situation and the time record reflects what happened.", "Use notes for exceptions: emergency calls, client-caused delays, traffic, weather, or unusual site access problems."], "Clean time records make payroll smoother and help managers fix scheduling problems instead of guessing at them.") },
      { title: "Missed punch corrections", body: lesson("Missed punch corrections", "A missed punch is not a crisis, but it must be corrected transparently. The correction request is the official path because it leaves an approval trail. Do not ask someone to edit time informally or wait until payroll closes unless you truly could not submit sooner.", ["Open your timekeeping page and choose the affected shift or pay period. Select the correction action rather than changing unrelated records.", "Enter the corrected time, the reason, and any job context the manager needs to verify it.", "Be specific: “forgot to clock out after Cahaba call; left site at 4:12 PM” is better than “forgot.”", "Watch for manager responses. If the correction is sent back, answer quickly so payroll is not delayed."], "A good correction request gives the approver enough information to say yes without a follow-up call.") },
      { title: "Quiz: pay period scenarios", body: lesson("Quiz: pay period scenarios", "This quiz checks whether you understand how time records move through the pay period. Focus on transparency: the best answer is usually the one that records the real event, explains exceptions, and routes changes through approval.", ["Choose correction requests for missed or wrong punches; do not pick informal edits or guessing.", "For breaks and travel, choose the answer that follows written policy and records exceptions.", "For pay period review, look for the response that checks entries before submission.", "Remember that managers can approve accurate records faster when notes are clear."], "Timekeeping is a shared control: you enter accurate facts, and managers review exceptions.") }
    ],
    quiz: "Quiz: pay period scenarios",
    quizQuestions: [
      { prompt: "You forgot to clock out after leaving a client site. What is the correct next step?", options: ["Submit a correction request with the actual departure time and reason", "Leave the shift running until tomorrow", "Ask a coworker to change it", "Delete the whole day"], correctIndex: 0, explanation: "Correction requests preserve the approval trail and explain what happened." },
      { prompt: "Why should job/site context be correct on a time entry?", options: ["Only payroll can see it", "It supports job costing, billing, and schedule review", "It changes your hourly rate automatically", "It is optional decoration"], correctIndex: 1, explanation: "Labor context affects reports beyond the paycheck." },
      { prompt: "A manager sends a correction back for clarification. You should:", options: ["Ignore it until payroll closes", "Reply with the requested detail promptly", "Submit a second unrelated request", "Ask another employee to approve it"], correctIndex: 1, explanation: "Fast clarification keeps the pay period moving." }
    ]
  },
  {
    id: "course-hub",
    title: "Using the Operations Hub (Software Training)",
    category: "software",
    duration: "40 min",
    description: "Hands-on tour of the daily dashboard, schedule, tickets, documents, and client communication tools.",
    lessons: [
      { title: "Dashboard tour", body: lesson("Dashboard tour", "The Operations Hub dashboard is the starting point for your day. It summarizes what needs action, where your work is scheduled, and which records changed recently. Use it as a launch pad, not as a replacement for detailed pages.", ["Review the top cards for current work: open tasks, timekeeping state, assigned training, and ticket activity.", "Use clickthroughs to open the underlying list instead of relying only on the number shown on the dashboard.", "Check recent activity for client messages, ticket updates, or project changes that may affect the day’s work.", "If your dashboard looks wrong, verify your viewer role and scope. Staff see self-scoped information; managers see direct reports; admins see broader operations."], "Start with the dashboard, then open the record before taking action.") },
      { title: "Schedule view", body: lesson("Schedule view", "The schedule view shows published shifts, open shifts, and swap requests. It helps staff know where to be and helps managers see coverage before problems reach clients. A shift is not just a calendar block; it carries site, time, and staffing context.", ["Review your week before the first shift. Confirm site names, start times, and any open shift opportunities.", "Claim open shifts only when you can work the time and location. The system records the claim for manager visibility.", "Use swap requests when you need coverage. Do not rely only on a text message, because managers need the request in the shared queue.", "Managers should check whether swaps keep coverage balanced before approval."], "The schedule is the shared source for coverage, so changes belong in the schedule workflow.") },
      { title: "Ticket notes", body: lesson("Ticket notes", "Tickets connect service work, client communication, and internal follow-up. Good ticket notes reduce repeat questions and make handoffs smoother. Every status change should have enough context for the next person to understand what happened.", ["Open the ticket before acting. Review priority, assignee, source, client, and message history.", "Use status honestly: open means not started, in progress means someone owns active work, waiting on client means external input is needed, and resolved means the issue has a clear closeout.", "Add comments with facts, not vague updates. Include readings, parts, access issues, client approvals, and next steps.", "If the ticket came from the client portal, write replies that are clear and client-safe; keep internal speculation out of client-facing notes."], "A ticket should tell the story of the work without needing a hallway conversation.") },
      { title: "Document uploads", body: lesson("Document uploads", "Documents in the Operations Hub include templates, generated files, signed records, and shared client documents. The document page is where staff can preview, send for signature, and confirm status without hunting through email.", ["Choose the correct client or project before generating or sharing a document. A file attached to the wrong client creates privacy and trust issues.", "Preview generated documents before sending. Check names, dates, scope, pricing, and signature requirements.", "Use the e-sign workflow for documents that need acceptance. The client portal updates the same status when the client signs.", "Keep document titles specific: client, purpose, and date are more useful than “new file.”"], "Documents should be easy to identify, safe to share, and tied to the correct client record.") },
      { title: "Client messages", body: lesson("Client messages", "Client messages are part of the same shared data spine as tickets, invoices, and projects. A message sent in the client portal can appear in the back office, and a staff reply can appear back to the client. That is useful only when replies are clear and appropriate.", ["Read the full thread before replying. Clients may have already answered a question or changed the request.", "Use plain language and avoid internal shorthand. “We are waiting on the condenser fan motor” is better than “parts issue.”", "Do not promise price, schedule, or scope changes unless you have authority and the record supports it.", "When a message should become a ticket or project update, open the related record so the work is tracked."], "Treat portal messages as client-facing records: concise, factual, and tied to action.") },
      { title: "Quiz: finding a work order", body: lesson("Quiz: finding a work order", "This quiz checks whether you can navigate from dashboard signals to the correct record. The goal is not memorizing clicks; it is choosing the place where the action belongs so the shared record stays complete.", ["Use dashboard tiles and recent activity to identify what changed, then open the underlying page.", "For schedule changes, use schedule workflows; for client issues, use tickets or messages; for documents, use the document record.", "Do not complete work from memory when the record might have changed.", "When role scope limits what you see, ask a manager instead of trying to work around the system."], "Good navigation keeps the work attached to the right record.") }
    ],
    quiz: "Quiz: finding a work order",
    quizQuestions: [
      { prompt: "A client replies in the portal about a project delay. Where should staff look first?", options: ["The shared message thread or related client record", "A personal text thread", "Payroll settings", "The course catalog"], correctIndex: 0, explanation: "Client portal replies land in shared client-facing records." },
      { prompt: "What is the safest way to handle a document before sending for signature?", options: ["Send immediately and check later", "Preview it and confirm client, scope, dates, and signature requirements", "Rename it after the client signs", "Attach it to any active client"], correctIndex: 1, explanation: "Previewing prevents wrong-client and wrong-scope mistakes." },
      { prompt: "A technician needs coverage for a shift. The proper system action is:", options: ["Only text a coworker", "Submit a swap request in scheduling", "Mark the shift complete", "Open a billing invoice"], correctIndex: 1, explanation: "Swap requests keep managers and coverage records in the loop." }
    ]
  },
  {
    id: "course-osha",
    title: "OSHA 10-Hour Safety Refresher",
    category: "safety",
    duration: "multi-part",
    description: "Core OSHA hazard recognition and reporting practices for field-service work.",
    lessons: [
      { title: "Hazard recognition", body: lesson("Hazard recognition", "Hazard recognition means noticing what can hurt people before work begins. In field service, hazards change by site: a brewery mechanical room, school roof, apartment electrical closet, or library basement can each present different risks. A short scan at the start prevents many incidents.", ["Look above, below, around, and inside the equipment area. Identify energized systems, moving parts, stored pressure, heat, chemicals, sharp edges, traffic, weather, and public access.", "Ask what changed since the job was scheduled. Water leaks, blocked access, active occupants, or other contractors can change the risk profile.", "Separate immediate hazards from ordinary inconvenience. An immediate fall, shock, chemical, or struck-by risk should stop work until controlled.", "Document hazards that affect the job, especially if they require client action or manager approval."], "Name the hazard, control it, then work. If you cannot control it, escalate before starting.", "This is OSHA training summary material, not an official OSHA 10 card course.") },
      { title: "PPE selection", body: lesson("PPE selection", "Personal protective equipment is the last line of defense after hazards are removed or controlled. PPE must match the task. Wearing gloves does not make energized work safe, and safety glasses do not protect against every chemical splash. Select PPE based on the exposure.", ["Inspect PPE before use. Cracked eye protection, torn gloves, damaged harnesses, or expired respirator cartridges should be removed from service.", "Match glove type to the hazard: cut resistance, chemical resistance, thermal protection, and electrical protection are different needs.", "Use eye and face protection when cutting, drilling, handling refrigerant, working overhead, or opening dusty or pressurized systems.", "Keep PPE clean and available. Gear left in the truck does not protect you in the mechanical room."], "PPE works only when it fits the hazard, fits the worker, and is worn before exposure starts.", "This is safety summary material; follow company policy and applicable OSHA requirements for required PPE.") },
      { title: "Jobsite communication", body: lesson("Jobsite communication", "Communication is a safety control. Many incidents happen because one person energized equipment, moved a ladder, opened a valve, or entered an area without knowing someone else was working. Clear jobsite communication keeps people from surprising each other.", ["Check in with the site contact when required. Confirm access, restricted areas, occupant concerns, and emergency procedures.", "Tell nearby workers what you are doing when your work affects them: shutting down equipment, blocking access, opening panels, using lifts, or creating noise/dust.", "Use simple, closed-loop communication. Ask the other person to confirm the plan instead of assuming they understood.", "Update dispatch or your manager when jobsite conditions affect safety, schedule, or client expectations."], "If your work could affect another person, communicate before the change happens.") },
      { title: "Incident reporting", body: lesson("Incident reporting", "Incident reporting is not about blame; it is about learning quickly and meeting legal, client, and company responsibilities. Injuries, property damage, vehicle incidents, chemical releases, electrical events, and near misses all deserve timely reporting.", ["Make the scene safe first. Get medical help or emergency response when needed before writing notes.", "Notify your manager as soon as practical. Delayed reporting makes facts harder to verify and can miss required timelines.", "Record facts: date, time, location, people involved, equipment, conditions, what happened, and immediate controls used.", "Preserve relevant evidence such as photos, damaged parts, or readings when safe to do so. Do not alter a scene if emergency response or investigation requires it."], "Report early, write facts, and let the review process determine next steps.", "This is summary material; official reporting obligations vary by incident and jurisdiction.") },
      { title: "Electrical awareness", body: lesson("Electrical awareness", "Electrical awareness is for everyone, even employees who are not electricians. Many HVAC and facilities tasks happen near panels, disconnects, controls, motors, and temporary power. Shock, arc flash, and unexpected startup are serious risks.", ["Assume equipment may be energized until verified by a qualified person using the correct meter and procedure.", "Respect approach boundaries and covers. Do not reach into panels or bypass guards unless you are authorized and trained for that task.", "Watch for warning signs: damaged cords, missing knockouts, burn marks, water near electrical gear, buzzing, unusual heat, or exposed conductors.", "Use lockout/tagout when servicing equipment that could unexpectedly energize or move."], "If you are not trained and authorized for the electrical task, stop at recognition and escalation.", "This is electrical safety summary material, not a substitute for qualified electrical training.") },
      { title: "Quiz: safe response", body: lesson("Quiz: safe response", "This quiz checks core OSHA-style hazard recognition and response. Pick the option that controls the hazard before production pressure, convenience, or assumptions. When the prompt mentions serious risk, the safe response is to pause and escalate.", ["Look for answers that identify the hazard and prevent exposure.", "Do not choose options that rely on luck, rushing, or another person noticing the issue later.", "Remember that PPE does not replace lockout/tagout, fall protection, or qualified electrical work.", "For incidents and near misses, early reporting is part of the safety system."], "Safe response means controlling the hazard before continuing.", "This quiz is internal summary training and does not issue an OSHA credential.") }
    ],
    quiz: "Quiz: safe response",
    quizQuestions: [
      { prompt: "You see water dripping near an electrical panel. What is the safest first action?", options: ["Open the panel quickly to inspect", "Ignore it if the floor is dry", "Stop, keep clear, and escalate to a qualified person", "Place cardboard under the drip"], correctIndex: 2, explanation: "Water near electrical equipment is a serious hazard requiring control and qualified review." },
      { prompt: "What is the purpose of near-miss reporting?", options: ["To punish whoever was closest", "To learn from a hazard before someone is injured", "To replace incident reporting", "To avoid documenting minor issues"], correctIndex: 1, explanation: "Near misses reveal weaknesses while there is still time to prevent injury." },
      { prompt: "PPE should be selected based on:", options: ["What is easiest to find", "The specific exposure and task", "What looks professional", "Only the weather"], correctIndex: 1, explanation: "Different hazards require different protective equipment." }
    ]
  },
  {
    id: "course-ladder",
    title: "Ladder & Fall Protection",
    category: "safety",
    duration: "30 min",
    description: "Practical ladder inspection, setup, tie-off, and fall-prevention scenarios from service calls.",
    lessons: [
      { title: "Inspecting your ladder", body: lesson("Inspecting your ladder", "A ladder inspection takes less than a minute and can prevent a severe fall. Inspect before each use, after transport, and any time the ladder is dropped or struck. A ladder that looks mostly fine can still fail if a rung, rail, foot, lock, or spreader is damaged.", ["Check rails and rungs for cracks, bends, corrosion, missing hardware, oil, mud, or other contamination.", "Confirm feet are present, clean, and gripping. Worn or missing feet can let the ladder slide even on a flat surface.", "For extension ladders, inspect locks, rope, pulleys, labels, and rung engagement before climbing.", "Remove damaged ladders from service immediately. Tag them or notify a manager so another employee does not unknowingly use them."], "Do not talk yourself into using a questionable ladder; replace the setup before climbing.", "This is fall-prevention summary material and does not replace required competent-person training.") },
      { title: "Three points of contact", body: "Three points of contact is the simplest habit that prevents most ladder falls. As you climb or descend, always keep either two hands and one foot, or two feet and one hand, in firm contact with the ladder. That way, if one grip slips, the other points still hold you.\n\n**Key practices:**\n- Face the ladder going up and down; never climb facing away.\n- Do not carry tools or materials in your hands. Use a tool belt or raise them with a hand line so both hands are free to grip.\n- Keep your body centered between the rails. If your belt buckle passes outside a rail, you are overreaching; climb down and reposition the ladder.\n- Maintain clean, dry boots and rungs. Mud, water, or grease can defeat your grip even when your technique is good.\n\n**Takeaway:** If you cannot keep three points of contact, stop and fix the setup before continuing." },
      { title: "Harness and tie-off basics", body: lesson("Harness and tie-off basics", "Fall protection equipment must be planned before the worker is exposed to the fall. A harness by itself does not protect anyone; it must fit correctly, connect to the right anchor, and be used with a lanyard or lifeline that limits fall distance and arrest forces.", ["Inspect the harness for cuts, burns, chemical damage, missing labels, damaged stitching, and distorted D-rings before use.", "Adjust the harness snugly. Loose straps can cause injury during fall arrest or allow a worker to slip out.", "Use only approved anchor points. Pipes, conduit, guardrails, and unknown roof structures are not automatically safe anchors.", "Plan rescue before climbing. Fall arrest can prevent impact but still leave a worker suspended and needing fast assistance."], "Fall protection is a system: harness, connector, anchor, clearance, and rescue plan must all work together.", "This is summary material; follow company fall-protection procedures and applicable regulations.") },
      { title: "Quiz: fall protection scenarios", body: lesson("Quiz: fall protection scenarios", "This quiz checks ladder and fall-protection decisions in common field conditions. Read for the hidden risk: overreaching, damaged equipment, carrying tools while climbing, or using an unapproved anchor. The safest answer fixes the setup before climbing or continuing.", ["Choose answers that keep the worker centered, connected, and using inspected equipment.", "Do not choose a shortcut that depends on strength, balance, or another person holding equipment steady.", "A damaged ladder or harness should be removed from service, not used carefully.", "When tie-off is required, the anchor and rescue plan matter as much as the harness."], "Preventing the fall is always better than hoping to recover from one.") }
    ],
    quiz: "Quiz: fall protection scenarios",
    quizQuestions: [
      { prompt: "While climbing a ladder, how many points of contact should you keep?", options: ["One", "Two", "Three", "Four"], correctIndex: 2, explanation: "Three points, either two hands and a foot or two feet and a hand, keep you stable if one grip slips." },
      { prompt: "What should you do with a ladder that has a cracked rail?", options: ["Use it only for short climbs", "Remove it from service and report it", "Tape the crack", "Have someone hold it"], correctIndex: 1, explanation: "Structural damage can cause failure and requires removal from service." },
      { prompt: "A harness protects you only when:", options: ["It is worn loosely", "It is connected to a complete fall-protection system", "It is stored in the truck", "It is used without inspecting it"], correctIndex: 1, explanation: "Harness, connector, anchor, clearance, and rescue planning all matter." }
    ]
  },
  {
    id: "course-loto",
    title: "Lockout/Tagout (LOTO) Procedures",
    category: "safety",
    duration: "35 min",
    description: "Step-by-step energy isolation, lock placement, verification, and handoff documentation.",
    lessons: [
      { title: "Energy sources", body: lesson("Energy sources", "Lockout/tagout begins with recognizing every energy source that could hurt someone or restart equipment unexpectedly. Electrical power is common, but it is not the only hazard. HVAC, mechanical, and facilities systems may also store pressure, gravity, heat, hydraulic force, pneumatic force, spring tension, or chemical energy.", ["Review the equipment and surrounding system before shutdown. Identify disconnects, valves, controls, stored pressure, moving parts, and any automatic start controls.", "Do not trust a switch, thermostat, or software command as isolation by itself. Control circuits can fail or be changed by another person.", "Release or restrain stored energy after isolation. Bleed pressure, block moving parts, discharge capacitors when qualified, and let hot surfaces cool.", "Ask for help when a system has multiple feeds or unfamiliar controls. Complex equipment often needs a manager or qualified person involved."], "LOTO protects against all hazardous energy, not just the obvious power switch.", "This is LOTO summary training; follow company procedures and applicable OSHA requirements.") },
      { title: "Lock placement", body: lesson("Lock placement", "A lock is a personal safety control. It tells everyone that a specific worker is protected by that isolation point and that the equipment must not be energized. Tags communicate the reason, person, and timing, but a tag alone does not physically prevent startup.", ["Use your own lock when you are exposed to the hazard. Do not borrow another person’s lock or ask someone else to lock out for you unless the written group procedure allows it.", "Place the lock on the correct energy-isolating device, such as a disconnect or valve, not on a start button or ordinary control switch.", "Attach a tag with your name, date, contact information, and reason for lockout so others know who controls the lock.", "Keep the key under your control. If a key is lost or a lock must be removed, follow the formal removal procedure."], "The person exposed to the hazard must be protected by the lockout, not merely by a verbal promise.") },
      { title: "Verification", body: lesson("Verification", "Verification is the step that proves isolation worked. Many severe injuries happen after someone shut equipment down but did not confirm that energy was actually controlled. Before touching equipment, test the system using the approved method for that energy type.", ["Try the normal start controls after lockout to confirm the equipment will not run. Return controls to the off or neutral position after testing.", "For electrical work, only qualified workers should test for absence of voltage using proper instruments and live-dead-live meter checks.", "Verify stored energy is released or controlled. Pressure gauges, moving parts, springs, and elevated components need attention after the main disconnect is off.", "If verification fails, stop and reassess the isolation plan. Do not continue because the equipment is quiet."], "Shutdown is not enough; verified zero hazardous energy is the goal.", "This summary does not authorize electrical testing unless you are trained and qualified.") },
      { title: "Release and handoff", body: lesson("Release and handoff", "Removing lockout is a controlled process because the system may be ready to move, heat, pressurize, or energize again. Before release, make sure people are clear, tools are removed, guards are replaced, and the equipment is ready for a safe return to service.", ["Inspect the work area. Remove tools, rags, jumpers, temporary blocks, and loose parts that could create a new hazard.", "Confirm guards, panels, covers, and access doors are restored unless a written test procedure requires otherwise.", "Notify affected employees and the site contact before re-energizing when the change could affect them.", "Each worker removes their own lock. If someone is absent, use the formal lock-removal process rather than improvising."], "A clean release prevents the repair from becoming the next incident.") },
      { title: "Quiz: LOTO scenarios", body: lesson("Quiz: LOTO scenarios", "This quiz checks whether you can identify hazardous energy, place locks correctly, verify isolation, and return equipment safely. The best answer follows the written process even when the job seems quick.", ["Look for all energy sources, including stored pressure or mechanical motion.", "Choose personal lock control over verbal agreements.", "Choose verification before contact with hazardous equipment.", "Choose formal handoff and release instead of shortcuts."], "LOTO is a sequence; skipping one step breaks the protection.", "This quiz is internal summary training, not a substitute for required LOTO qualification.") }
    ],
    quiz: "Quiz: LOTO scenarios",
    quizQuestions: [
      { prompt: "Which is an energy source that may need control besides electricity?", options: ["Stored pressure", "The job number", "The client name", "A clean filter"], correctIndex: 0, explanation: "Pressure, gravity, heat, and mechanical motion can all be hazardous energy." },
      { prompt: "Where should a lock be placed?", options: ["On a start button", "On the correct energy-isolating device", "On the invoice", "On a coworker’s toolbox"], correctIndex: 1, explanation: "The lock must control the device that isolates hazardous energy." },
      { prompt: "Before touching locked-out equipment, you should:", options: ["Assume the disconnect worked", "Verify isolation using the approved method", "Remove your tag", "Ask the client to test it"], correctIndex: 1, explanation: "Verification proves the hazardous energy has been controlled." }
    ]
  },
  {
    id: "course-driving",
    title: "Defensive Driving / Fleet Safety",
    category: "safety",
    duration: "30 min",
    description: "Daily vehicle checks, route behavior, backing safety, and incident response for fleet drivers.",
    lessons: [
      { title: "Vehicle inspection", body: lesson("Vehicle inspection", "A vehicle inspection is a safety check and a reliability check. Service vehicles carry tools, parts, ladders, and company branding, so a preventable breakdown or loose load can hurt people and delay clients. Inspect before the first trip and whenever conditions change.", ["Walk around the vehicle. Check tires, lights, mirrors, windshield, wipers, ladder rack, visible leaks, and body damage.", "Secure cargo. Tools, cylinders, parts, and ladders should not shift, fall, or become projectiles during sudden braking.", "Confirm required documents and emergency items are present: registration, insurance card, incident kit, cones or triangles if provided, and basic first-aid supplies.", "Report defects before driving when they affect safety. Do not take a vehicle with unsafe tires, brake concerns, loose ladders, or major visibility problems."], "A few minutes before departure can prevent a roadside emergency later.") },
      { title: "Urban routes", body: lesson("Urban routes", "Urban driving creates dense risk: pedestrians, cyclists, delivery trucks, tight turns, blocked lanes, and impatient traffic. Defensive driving means expecting that someone may not see your vehicle and leaving yourself time and space to respond.", ["Plan the route before moving. Set navigation while parked, review parking options, and avoid last-second lane changes.", "Maintain following distance. Loaded service vehicles need more stopping room than a passenger car.", "Scan intersections before entering, even with a green light. Look for pedestrians, red-light runners, emergency vehicles, and turning traffic.", "Avoid distractions. Calls, messages, and route changes should be handled hands-free according to policy or while safely parked."], "Drive as if your schedule matters, but everyone’s safety matters more.") },
      { title: "Backing and parking", body: lesson("Backing and parking", "Backing incidents are common because visibility is limited and job sites are busy. The safest backing move is the one you avoid. Choose parking that allows you to pull forward when leaving whenever practical.", ["Before backing, scan the area for people, posts, low obstacles, equipment, shopping carts, children, and uneven ground.", "Use mirrors and cameras, but do not rely on them alone. Cameras can miss side hazards and mirrors have blind spots.", "Back slowly and stop immediately if you lose sight of the path or if someone enters the area.", "Use a spotter when available, but remember the driver remains responsible for the vehicle’s movement."], "If backing feels uncertain, stop, get out, and look before continuing.") },
      { title: "Incident response", body: lesson("Incident response", "A vehicle incident response should be calm, factual, and focused on safety first. Whether the event is a collision, property damage, load shift, or near miss, your actions immediately afterward affect injuries, claims, client trust, and company learning.", ["Move to a safe location if possible and check for injuries. Call emergency services when anyone may be hurt or the scene is unsafe.", "Notify your manager according to policy. Do not negotiate fault, promise payment, or argue at the scene.", "Document facts: location, time, weather, vehicles, photos, witness information, police report number if applicable, and damage.", "Secure tools, ladders, refrigerant, or materials if the incident affected cargo. Do not continue driving an unsafe vehicle."], "After an incident, protect people, report promptly, and document facts without guessing.") },
      { title: "Quiz: fleet scenarios", body: lesson("Quiz: fleet scenarios", "This quiz checks daily driving decisions for service vehicles. The safest answer usually increases space, improves visibility, secures cargo, or pauses the trip until a hazard is controlled.", ["Look for answers that prevent backing or make backing slower and more visible.", "Choose reporting and inspection over continuing with a known defect.", "For incidents, choose safety and factual documentation over arguments or promises.", "Remember that a loaded service vehicle handles differently than a personal car."], "Fleet safety is part of the service call, not just the travel between calls.") }
    ],
    quiz: "Quiz: fleet scenarios",
    quizQuestions: [
      { prompt: "What should you do if a ladder rack is loose before departure?", options: ["Drive slowly", "Report it and do not drive until secured", "Tie it with a loose rag", "Ignore it for short routes"], correctIndex: 1, explanation: "Loose exterior cargo is a serious road hazard." },
      { prompt: "The safest backing practice is to:", options: ["Back quickly before traffic arrives", "Avoid backing when practical and get out to look when unsure", "Use only the camera", "Assume pedestrians will move"], correctIndex: 1, explanation: "Avoiding backing or verifying the path reduces common collision risk." },
      { prompt: "After a vehicle incident, you should avoid:", options: ["Checking for injuries", "Calling emergency services if needed", "Promising fault or payment at the scene", "Documenting facts"], correctIndex: 2, explanation: "Do not negotiate fault; report and document facts." }
    ]
  },
  {
    id: "course-electrical",
    title: "Electrical Safety Fundamentals",
    category: "compliance",
    duration: "50 min",
    description: "Electrical approach boundaries, arc-flash basics, meter safety, and de-energized work habits.",
    lessons: [
      { title: "Arc flash basics", body: lesson("Arc flash basics", "Arc flash is a rapid release of energy caused by an electrical fault. It can create extreme heat, pressure, light, sound, and flying metal. Even workers who are not performing electrical repairs need to recognize arc-flash risk around panels, disconnects, switchgear, and damaged equipment.", ["Do not open electrical equipment unless you are trained and authorized for the task.", "Look for warning labels, missing covers, burn marks, unusual heat, buzzing, corrosion, or water exposure near energized gear.", "Keep unqualified people outside the work area when electrical equipment is exposed or being tested.", "Use de-energized work methods whenever possible, with proper lockout/tagout and verification by qualified personnel."], "Respect electrical equipment before it gives you a reason to fear it.", "This is electrical safety summary material, not authorization for energized electrical work.") },
      { title: "Panel approach boundaries", body: lesson("Panel approach boundaries", "Approach boundaries define who may get close to exposed energized parts and under what conditions. They exist because electrical injury can happen without direct contact when voltage, tools, or body position create a path. Unqualified workers should maintain distance and involve qualified personnel.", ["Do not reach into a panel, remove barriers, or cross into exposed electrical space unless you are trained and assigned to that work.", "Keep tools, ladders, tape measures, and metal parts away from exposed energized components.", "Control the area around open equipment so clients, occupants, and other trades do not walk into the hazard.", "If a cover is missing or a panel is damaged, treat it as a hazard and escalate instead of working around it."], "Distance is a control; use it until a qualified person makes the equipment safe.", "This summary supports awareness only and does not replace NFPA 70E or employer-required training.") },
      { title: "Meter safety", body: lesson("Meter safety", "Meters are useful only when used correctly by qualified workers. The wrong meter setting, damaged leads, poor contact, or an underrated meter can create shock or arc-flash hazards. Meter safety starts before the probes touch anything.", ["Inspect the meter and leads. Look for cracked insulation, damaged probes, loose jacks, low battery, and correct category rating for the environment.", "Use the correct setting and range before testing. Never move leads between jacks while connected to a circuit.", "Use a live-dead-live check when verifying absence of voltage: test a known live source, test the circuit, then retest the known live source.", "Keep fingers behind probe guards and use one-hand techniques when trained to reduce current path risk."], "A meter is safety equipment only when it is rated, inspected, configured, and used by a qualified person.", "This material is a summary and does not qualify a worker to perform electrical testing.") },
      { title: "De-energized work", body: lesson("De-energized work", "De-energized work is the preferred method because it removes the electrical hazard before hands enter the equipment. Turning a switch off is not the same as creating an electrically safe work condition. The process includes isolation, lockout/tagout, verification, and control of stored energy.", ["Identify all power sources, including secondary feeds, controls, generators, and backfeed possibilities.", "Apply lockout/tagout to the energy-isolating device according to procedure.", "Verify absence of voltage using qualified-person methods and proper equipment.", "Maintain the safe condition until work is complete, covers are restored, and the release process is followed."], "If electrical work can be de-energized, plan it that way instead of treating energized work as normal.", "This summary does not replace qualified electrical safety training.") },
      { title: "Quiz: electrical calls", body: lesson("Quiz: electrical calls", "This quiz checks electrical awareness, not advanced electrical qualification. Choose the answer that keeps unqualified people away from exposed hazards and uses qualified workers for testing, panel access, and de-energized work.", ["Do not choose answers that involve reaching into panels without authorization.", "Look for water, damage, heat, and missing covers as warning signs.", "Choose proper lockout/tagout and verification before work.", "Treat meters as specialized tools requiring inspection and qualification."], "Electrical safety starts with recognizing your limits and controlling exposure.", "This quiz is internal awareness training, not a license or certification.") }
    ],
    quiz: "Quiz: electrical calls",
    quizQuestions: [
      { prompt: "What should an unqualified worker do when a panel cover is missing?", options: ["Reach in carefully", "Treat it as a hazard and escalate", "Tape paper over it", "Continue if the lights are on"], correctIndex: 1, explanation: "Missing covers can expose energized parts and require qualified attention." },
      { prompt: "A live-dead-live meter check is used to:", options: ["Verify the meter and absence of voltage", "Measure refrigerant pressure", "Replace lockout/tagout", "Speed up billing"], correctIndex: 0, explanation: "It confirms the tester works before and after checking the circuit." },
      { prompt: "Preferred electrical work practice is generally:", options: ["Work energized whenever faster", "De-energize, lock out, and verify when possible", "Ask the client to watch", "Use any meter available"], correctIndex: 1, explanation: "De-energized verified work reduces electrical exposure." }
    ]
  },
  {
    id: "course-epa",
    title: "EPA 608 Refrigerant Handling",
    category: "compliance",
    duration: "multi-part",
    description: "Refrigerant recovery, leak thresholds, cylinder handling, and documentation for recertification.",
    lessons: [
      { title: "Recovery rules", body: lesson("Recovery rules", "Refrigerant recovery protects the environment and keeps work compliant. Venting regulated refrigerant is prohibited except in narrow situations defined by regulation. Technicians must use approved recovery equipment and handle refrigerant according to the system type and service activity.", ["Identify the refrigerant before recovery. Mixing refrigerants can contaminate cylinders and create disposal problems.", "Use recovery equipment and cylinders rated for the refrigerant and pressure involved.", "Recover to the required level for the work being performed and follow equipment instructions for shutdown and hose clearing.", "Label recovered refrigerant and keep it separated when purity is uncertain."], "Do not treat refrigerant as ordinary air; recover, label, and document it correctly.", "This is EPA 608 training summary material. EPA 608 certification requires an approved provider and exam.") },
      { title: "Leak thresholds", body: lesson("Leak thresholds", "Leak requirements depend on equipment type, refrigerant amount, and current regulation. The important field habit is to take leaks seriously: identify, document, communicate, and repair according to company and regulatory expectations. A small leak can become a compliance issue when ignored.", ["Record symptoms and readings that indicate a leak: low charge, oil staining, detector response, pressure trends, or repeated recharge history.", "Do not add refrigerant repeatedly without addressing the likely leak path and documentation requirements.", "Escalate equipment that may cross regulatory thresholds or require repair timelines.", "Explain findings to the client in plain language without overstating certainty beyond your evidence."], "A leak note should make the next compliance decision easier, not harder.", "This lesson is a summary; always follow current EPA rules and company procedures.") },
      { title: "Cylinder handling", body: lesson("Cylinder handling", "Refrigerant cylinders are pressure vessels and must be handled with care. Incorrect filling, storage, transport, or mixing can create safety and compliance problems. Treat every cylinder as labeled, pressurized equipment.", ["Verify cylinder rating, refrigerant type, condition, and hydrostatic date where applicable before use.", "Do not overfill. Use a scale and follow maximum fill limits, allowing for temperature expansion.", "Keep cylinders upright and secured during transport. Protect valves and avoid heat exposure.", "Separate virgin, recovered, reclaimed, and waste refrigerant according to policy so material is not contaminated."], "Cylinder handling is part safety and part chain-of-custody; control both.") },
      { title: "Recordkeeping", body: lesson("Recordkeeping", "Refrigerant records support compliance, client reporting, and future diagnosis. A good record connects the equipment, refrigerant, amount recovered or added, leak findings, repair action, and technician. Incomplete records make repeat work and compliance review harder.", ["Record equipment identifiers such as location, model, serial number, and client site when available.", "Document refrigerant type and amounts added, recovered, transferred, or disposed according to procedure.", "Attach leak notes, repair notes, and verification readings so the record explains the decision.", "Submit required logs promptly. Waiting until the end of the month increases the chance of missing details."], "If refrigerant moved, the record should say what moved, how much, why, and where it went.", "This is summary guidance and does not replace official EPA recordkeeping requirements.") },
      { title: "Recert review", body: lesson("Recert review", "EPA 608 certification confirms knowledge of refrigerant regulations and handling practices. Internal refresher training helps technicians stay sharp, but it does not replace the approved exam or any required recertification process. Treat this review as preparation and reinforcement.", ["Review core concepts: recovery, recycling, reclamation, leak repair, substitute refrigerants, oils, evacuation, and cylinder safety.", "Know your limits. If a task requires certification or specialized equipment you do not have, escalate before handling refrigerant.", "Stay current. Refrigerant rules and acceptable substitutes can change, and company procedures may update accordingly.", "Keep proof of certification available according to company policy."], "Internal refreshers support good practice; official certification comes from approved testing.") },
      { title: "Quiz: refrigerant scenarios", body: lesson("Quiz: refrigerant scenarios", "This quiz checks practical refrigerant-handling decisions. Choose the answer that recovers refrigerant properly, prevents mixing, documents accurately, and recognizes when official EPA certification or current rules apply.", ["Do not choose venting or repeated top-offs as normal practice.", "Choose scale-based cylinder filling and secure transport.", "Choose documentation that identifies refrigerant type and amount.", "Remember this training summary does not issue EPA 608 certification."], "Compliant refrigerant work is controlled, measured, and documented.", "EPA 608 certification requires an approved provider and exam.") }
    ],
    quiz: "Quiz: refrigerant scenarios",
    quizQuestions: [
      { prompt: "What should you do before recovering refrigerant?", options: ["Identify the refrigerant type", "Open the system to atmosphere", "Mix it with any cylinder", "Skip labeling"], correctIndex: 0, explanation: "Identification prevents mixing and supports correct recovery handling." },
      { prompt: "Why use a scale when filling a recovery cylinder?", options: ["To avoid overfilling", "To estimate labor hours", "To test voltage", "To check ladder angle"], correctIndex: 0, explanation: "Weight limits prevent dangerous overfill as temperature changes." },
      { prompt: "Does this internal refresher issue EPA 608 certification?", options: ["Yes, automatically", "Only for managers", "No, certification requires an approved provider and exam", "Only if the quiz is passed twice"], correctIndex: 2, explanation: "Official EPA 608 certification requires approved testing." }
    ]
  },
  {
    id: "course-first-aid",
    title: "Bloodborne Pathogens & First Aid",
    category: "compliance",
    duration: "25 min",
    description: "Exposure control, first-aid kit use, incident reporting, and cleanup expectations.",
    lessons: [
      { title: "Exposure basics", body: lesson("Exposure basics", "Bloodborne pathogen awareness helps workers avoid contact with blood or other potentially infectious materials. Field employees may encounter injuries, discarded sharps, contaminated surfaces, or cleanup needs at client sites. The first control is distance: do not touch what you are not trained and equipped to handle.", ["Treat blood and certain body fluids as potentially infectious. Do not rely on appearance to judge safety.", "Use gloves and other barriers when providing first aid within your training level, and wash hands afterward even if gloves were worn.", "Do not pick up sharps by hand. Secure the area and follow company or site procedure for safe removal.", "Report any exposure involving broken skin, eyes, mouth, or contaminated sharps immediately so medical evaluation can happen quickly."], "Protect yourself first; you cannot help effectively if you become the second injured person.", "This is bloodborne pathogens summary material and does not replace required OSHA exposure-control training.") },
      { title: "First aid kit use", body: lesson("First aid kit use", "A first aid kit supports immediate care for minor injuries and helps stabilize a situation until professional help arrives. Use only the supplies and actions you are trained to use. For serious bleeding, breathing difficulty, chest pain, head injury, electrical shock, chemical exposure, or loss of consciousness, call emergency services.", ["Know where the kit is kept in the vehicle or facility and check that basic supplies are present and usable.", "Wear gloves when there is any chance of contact with blood or body fluids.", "Use dressings and pressure for minor bleeding when trained, and avoid applying creams or medications unless policy allows.", "After use, report depleted supplies so the kit is restocked before the next incident."], "First aid is immediate, limited help; serious conditions need emergency response.") },
      { title: "Cleanup and reporting", body: lesson("Cleanup and reporting", "Cleanup after an injury or exposure must be controlled. Ordinary housekeeping is not enough when blood, sharps, or potentially infectious material may be present. The priority is to isolate the area, prevent contact, and involve trained cleanup resources according to policy.", ["Block access to the affected area so employees, clients, or occupants do not walk through contamination.", "Use appropriate gloves, bags, disinfectants, and disposal methods only if you are trained and assigned to perform cleanup.", "Report exposures and near misses promptly. Time matters for medical evaluation after potential bloodborne exposure.", "Document facts: who was involved, where it happened, what material was present, PPE used, and who was notified."], "After a potential exposure, fast reporting is part of the medical control, not paperwork for later.", "This is summary training; follow the written exposure control plan and site requirements.") },
      { title: "Quiz: response scenarios", body: lesson("Quiz: response scenarios", "This quiz checks bloodborne pathogen awareness and basic first-aid response. Choose answers that protect the responder, control the area, call for appropriate help, and report exposures quickly.", ["Do not choose bare-hand contact with blood or sharps.", "For serious symptoms, choose emergency services instead of waiting.", "For cleanup, choose trained procedures and controlled access.", "For exposure, choose immediate reporting and medical evaluation."], "Safe first aid starts with responder protection and quick escalation when needed.", "This quiz is internal summary training and does not replace required first-aid or bloodborne certification.") }
    ],
    quiz: "Quiz: response scenarios",
    quizQuestions: [
      { prompt: "What should you do before helping with a bleeding injury within your training level?", options: ["Put on gloves or an appropriate barrier", "Use bare hands to save time", "Ignore the injury", "Ask the client for a towel only"], correctIndex: 0, explanation: "Barriers reduce exposure risk when blood may be present." },
      { prompt: "A used needle is found near your work area. What is the safest response?", options: ["Pick it up by hand", "Kick it aside", "Secure the area and follow sharps procedure", "Hide it under debris"], correctIndex: 2, explanation: "Sharps require controlled handling by trained people." },
      { prompt: "Potential blood exposure to the eye should be:", options: ["Reported immediately for medical guidance", "Ignored if it does not hurt", "Handled at the next annual review", "Covered with tape"], correctIndex: 0, explanation: "Prompt reporting supports timely medical evaluation." }
    ]
  },
  {
    id: "course-customer",
    title: "Customer Service Excellence in the Field",
    category: "soft skills",
    duration: "30 min",
    description: "Arrival etiquette, clean closeouts, explaining delays, and protecting trust on every call.",
    lessons: [
      { title: "Arrival etiquette", body: lesson("Arrival etiquette", "The first five minutes of a visit shape the client’s confidence. Arrival etiquette is not about being formal; it is about making the client feel informed, respected, and safe having you on site. A good arrival reduces friction before technical work begins.", ["Park where instructed and avoid blocking entrances, loading areas, fire lanes, or tenant access unless approved.", "Check in with the site contact, introduce yourself, state the company, and confirm the reason for the visit.", "Ask about access rules, occupant concerns, restricted areas, alarms, pets, or business operations that may affect the work.", "Set a simple expectation: what you will inspect first and when you will update them."], "A professional arrival tells the client their property and time matter.") },
      { title: "Explaining delays", body: lesson("Explaining delays", "Delays happen because parts, access, weather, safety conditions, or diagnosis can change. What damages trust is silence or vague language. Clients can usually handle bad news better than uncertainty, especially when you explain the next step.", ["State the fact plainly: what is delayed and why. Avoid blaming dispatch, suppliers, or coworkers in front of the client.", "Give the next action, not just the problem. For example, say that you are checking part availability and will update dispatch within a specific window.", "Avoid promises you cannot control, such as exact arrival times for parts or final pricing without approval.", "Document the delay in the ticket so office staff can answer follow-up questions consistently."], "A delay with a clear next step feels managed; a delay with silence feels ignored.") },
      { title: "Clean closeout", body: lesson("Clean closeout", "A clean closeout turns technical work into a complete service experience. The client should know what was done, what changed, what remains, and what they need to do next. The work area should look controlled and intentional, not abandoned.", ["Clean the immediate work area: remove packaging, replaced parts if policy allows, debris, and tools.", "Restore access panels, covers, ceiling tiles, thermostats, or settings that were changed during work unless otherwise documented.", "Explain the result in client-safe language: what you found, what you fixed, what you verified, and any recommended follow-up.", "Update the ticket before leaving so the office record matches what the client heard."], "Closeout is complete when the site is clean, the client is informed, and the record is updated.") },
      { title: "Quiz: service recovery", body: lesson("Quiz: service recovery", "This quiz checks field communication decisions. Choose responses that are clear, respectful, factual, and connected to the shared record. Good customer service does not mean saying yes to everything; it means setting honest expectations and following through.", ["For arrival, choose check-in and confirmation over wandering directly to equipment.", "For delays, choose early updates and next actions.", "For closeout, choose plain-language explanation and clean work areas.", "Avoid promises outside your authority."], "Trust is built by clarity, respect, and follow-through.") }
    ],
    quiz: "Quiz: service recovery",
    quizQuestions: [
      { prompt: "What should you do when arriving at a client site?", options: ["Go directly anywhere you want", "Check in, introduce yourself, and confirm the visit purpose", "Wait silently in the parking lot", "Ask another client where to go"], correctIndex: 1, explanation: "A clear check-in sets expectations and respects site rules." },
      { prompt: "A part delay occurs. The best client update is:", options: ["Say nothing until they ask", "Blame the supplier angrily", "Explain the delay and the next action you are taking", "Promise a time you cannot control"], correctIndex: 2, explanation: "Clients need facts and next steps, not silence or unsupported promises." },
      { prompt: "A clean closeout includes:", options: ["Leaving tools in place", "Explaining findings and updating the ticket", "Only telling the coworker", "Skipping documentation"], correctIndex: 1, explanation: "The client and record should both reflect the completed work." }
    ]
  },
  {
    id: "course-difficult",
    title: "Handling Difficult Customers",
    category: "soft skills",
    duration: "25 min",
    description: "De-escalation language, when to call a manager, and how to document tense interactions.",
    lessons: [
      { title: "De-escalation", body: lesson("De-escalation", "A difficult customer interaction is usually driven by stress: downtime, cost, repeated problems, or poor communication before you arrived. De-escalation starts with lowering the temperature. Your goal is not to win an argument; it is to keep the conversation safe and move it toward facts and next steps.", ["Use calm, short sentences. Acknowledge the concern without accepting blame you cannot verify.", "Ask one focused question at a time so the customer can provide useful details.", "Avoid defensive language, sarcasm, interrupting, or arguing about previous visits.", "Set boundaries if language becomes abusive or unsafe: you can pause the conversation and involve a manager."], "Calm does not mean passive; it means controlled, respectful, and focused on resolution.") },
      { title: "When to call a manager", body: lesson("When to call a manager", "Some situations should move to a manager quickly. Escalation is not failure; it protects the client relationship and keeps field staff from making commitments they are not authorized to make. Call before the situation becomes a complaint that surprises the office.", ["Escalate threats, harassment, unsafe behavior, refusal of access after dispatch, or any situation where you feel physically unsafe.", "Escalate pricing disputes, warranty demands, requests for free work, or promises about schedule that exceed your authority.", "Escalate repeated callbacks, major equipment failure, property damage, or client claims that conflict with the record.", "When calling, provide facts: client, site, issue, what was said, what you observed, and what decision is needed."], "Escalate early when authority, safety, or client trust is at stake.") },
      { title: "Documentation", body: lesson("Documentation", "Documentation after a tense interaction must be factual and professional. The record may be read by managers, office staff, or the client-facing team later. Emotional labels rarely help; specific words, actions, times, and decisions do.", ["Write observable facts: who was present, what request was made, what information you provided, and what next step was agreed.", "Avoid insults, speculation, or personal opinions. A note should describe behavior and decisions, not attack a person.", "Record commitments carefully. If a manager approved a next step, note who approved it and when.", "Attach photos, readings, or ticket references that support the technical issue."], "Good documentation lets the company respond consistently without escalating the emotion.") },
      { title: "Quiz: hard conversations", body: lesson("Quiz: hard conversations", "This quiz checks de-escalation, escalation, and documentation choices. Choose the answer that stays calm, protects safety, avoids unauthorized promises, and records facts professionally.", ["Choose acknowledgement without accepting unknown blame.", "Escalate safety concerns, threats, pricing disputes, and commitments outside your authority.", "Document what happened without insults or speculation.", "Use the manager as a resource before the situation gets worse."], "The best response keeps the person safe and the record useful.") }
    ],
    quiz: "Quiz: hard conversations",
    quizQuestions: [
      { prompt: "A customer is angry about repeated downtime. What is a good first response?", options: ["Argue that it is not your fault", "Acknowledge the frustration and ask a focused question", "Leave without telling anyone", "Promise free replacement"], correctIndex: 1, explanation: "Acknowledgement and focused questions lower tension and gather facts." },
      { prompt: "Which situation should be escalated to a manager?", options: ["A routine filter change", "A request for free work or a pricing dispute", "A clean closeout", "A normal clock-in"], correctIndex: 1, explanation: "Pricing and free-work requests exceed normal field authority." },
      { prompt: "Which note is most professional?", options: ["Client was impossible", "Client shouted that this was the third outage this month; manager notified at 2:10 PM", "Client is always wrong", "Bad vibes"], correctIndex: 1, explanation: "It records observable facts and the escalation without insults." }
    ]
  },
];
