insert into public.gf1_inventory_items (
  id,
  name,
  category,
  status,
  icon
) values
  ('mon-asus-01', 'ASUS Monitor 01', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-02', 'ASUS Monitor 02', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-03', 'ASUS Monitor 03', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-04', 'ASUS Monitor 04', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-05', 'ASUS Monitor 05', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-06', 'ASUS Monitor 06', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-07', 'ASUS Monitor 07', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-08', 'ASUS Monitor 08', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-09', 'ASUS Monitor 09', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-10', 'ASUS Monitor 10', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-11', 'ASUS Monitor 11', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-12', 'ASUS Monitor 12', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-13', 'ASUS Monitor 13', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-14', 'ASUS Monitor 14', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-asus-15', 'ASUS Monitor 15', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-sceptre-01', 'Sceptre Monitor 01', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-sceptre-02', 'Sceptre Monitor 02', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-sceptre-03', 'Sceptre Monitor 03', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-sceptre-04', 'Sceptre Monitor 04', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-sceptre-05', 'Sceptre Monitor 05', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-acer-01', 'Acer Monitor 01', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-acer-02', 'Acer Monitor 02', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-viewsonic-01', 'ViewSonic Monitor 01', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-viewsonic-02', 'ViewSonic Monitor 02', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-viewsonic-03', 'ViewSonic Monitor 03', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-dell-01', 'Dell Monitor 01', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-dell-02', 'Dell Monitor 02', 'monitors', 'available', 'fa-solid fa-display'),
  ('mon-lg-01', 'LG Monitor 01', 'monitors', 'available', 'fa-solid fa-display')
on conflict (id) do nothing;
