insert into public.plans (code, name, monthly_price_cents, annual_price_cents, stripe_product_id, stripe_monthly_price_id, stripe_annual_price_id, min_seats, features, sort_order)
values
  ('starter','Starter',1000,9600,'prod_replace_starter','price_replace_starter_month','price_replace_starter_year',2,'{"projects":false,"invoicing":false,"shifts":false,"chat":false,"legal":false,"reporting":false}'::jsonb,10),
  ('pro','Pro',1800,17280,'prod_replace_pro','price_replace_pro_month','price_replace_pro_year',2,'{"projects":true,"invoicing":true,"shifts":false,"chat":false,"legal":false,"reporting":false}'::jsonb,20),
  ('business','Business',2800,26880,'prod_replace_business','price_replace_business_month','price_replace_business_year',2,'{"projects":true,"invoicing":true,"shifts":true,"chat":true,"legal":false,"reporting":true}'::jsonb,30),
  ('legal','Legal',5500,52800,'prod_replace_legal','price_replace_legal_month','price_replace_legal_year',2,'{"projects":true,"invoicing":true,"shifts":true,"chat":true,"legal":true,"reporting":true}'::jsonb,40)
on conflict (code) do update set
  name = excluded.name,
  monthly_price_cents = excluded.monthly_price_cents,
  annual_price_cents = excluded.annual_price_cents,
  features = excluded.features,
  sort_order = excluded.sort_order;

insert into public.utbms_task_codes (code, category, name, description) values
('L100','Litigation','Case Assessment, Development and Administration','Initial case assessment and ongoing administration.'),
('L110','Litigation','Fact Investigation/Development','Investigation and development of facts.'),
('L120','Litigation','Analysis/Strategy','Case analysis and strategy.'),
('L130','Litigation','Experts/Consultants','Work with experts and consultants.'),
('L140','Litigation','Document/File Management','Document and file management.'),
('L150','Litigation','Budgeting','Budget preparation and management.'),
('L160','Litigation','Settlement/Non-Binding ADR','Settlement and non-binding dispute resolution.'),
('L190','Litigation','Other Case Assessment, Development and Administration','Other case assessment work.'),
('L200','Litigation','Pre-Trial Pleadings and Motions','Pleadings and motion practice before trial.'),
('L210','Litigation','Pleadings','Pleadings.'),
('L220','Litigation','Preliminary Injunctions/Provisional Remedies','Preliminary injunctions and provisional remedies.'),
('L230','Litigation','Court Mandated Conferences','Court mandated conferences.'),
('L240','Litigation','Dispositive Motions','Dispositive motions.'),
('L250','Litigation','Other Written Motions and Submissions','Other motions and submissions.'),
('L260','Litigation','Class Action Certification and Notice','Class certification and notice.'),
('L300','Litigation','Discovery','Discovery.'),
('L310','Litigation','Written Discovery','Written discovery.'),
('L320','Litigation','Document Production','Document production.'),
('L330','Litigation','Depositions','Depositions.'),
('L340','Litigation','Expert Discovery','Expert discovery.'),
('L350','Litigation','Discovery Motions','Discovery motions.'),
('L390','Litigation','Other Discovery','Other discovery.'),
('L400','Litigation','Trial Preparation and Trial','Trial preparation and trial.'),
('L410','Litigation','Fact Witnesses','Fact witnesses.'),
('L420','Litigation','Expert Witnesses','Expert witnesses.'),
('L430','Litigation','Written Motions and Submissions','Written trial motions and submissions.'),
('L440','Litigation','Other Trial Preparation and Support','Other trial preparation and support.'),
('L450','Litigation','Trial and Hearing Attendance','Trial and hearing attendance.'),
('L460','Litigation','Post-Trial Motions and Submissions','Post-trial motions and submissions.'),
('L470','Litigation','Enforcement','Enforcement.'),
('L500','Litigation','Appeal','Appeal.'),
('L510','Litigation','Appellate Motions and Submissions','Appellate motions and submissions.'),
('L520','Litigation','Appellate Briefs','Appellate briefs.'),
('L530','Litigation','Oral Argument','Oral argument.'),
('L600','Litigation','e-Discovery','Electronic discovery.'),
('L610','Litigation','Identification','e-Discovery identification.'),
('L620','Litigation','Preservation','e-Discovery preservation.'),
('L630','Litigation','Collection','e-Discovery collection.'),
('L640','Litigation','Processing','e-Discovery processing.'),
('L650','Litigation','Review','e-Discovery review.'),
('L660','Litigation','Analysis','e-Discovery analysis.'),
('L670','Litigation','Production','e-Discovery production.'),
('L680','Litigation','Presentation','e-Discovery presentation.'),
('P100','Project','Project Administration','Project administration.'),
('P200','Project','Project Planning','Project planning.'),
('P300','Project','Project Implementation','Project implementation.'),
('P400','Project','Project Monitoring','Project monitoring.'),
('P500','Project','Project Completion','Project completion.'),
('C100','Counseling','Fact Gathering','Counseling fact gathering.'),
('C200','Counseling','Researching Law','Counseling legal research.'),
('C300','Counseling','Analysis and Advice','Counseling analysis and advice.'),
('B100','Bankruptcy','Administration','Bankruptcy administration.'),
('B200','Bankruptcy','Operations','Bankruptcy operations.'),
('B300','Bankruptcy','Claims and Plan','Bankruptcy claims and plan.'),
('B400','Bankruptcy','Bankruptcy-Related Advice','Bankruptcy-related advice.')
on conflict (code) do update set category = excluded.category, name = excluded.name, description = excluded.description;

insert into public.utbms_activity_codes (code, name, description) values
('A101','Plan and prepare for','Planning or preparation associated with a matter.'),
('A102','Research','Legal or factual research associated with the matter.'),
('A103','Draft/Revise','Drafting or revision of documents or other material.'),
('A104','Review/Analyze','Review or analysis of documents or other material.'),
('A105','Communicate (within legal team)','Internal communications within the legal team.'),
('A106','Communicate (with client)','Communications with client.'),
('A107','Communicate (opponents/other outside counsel)','Communications with opposing counsel or other outside counsel.'),
('A108','Communicate (other external)','Communications with other external parties.'),
('A109','Appear for/attend','Appearances and attendance.'),
('A110','Manage data/files','Data, file, and document management.'),
('A111','Other','Other activity.')
on conflict (code) do update set name = excluded.name, description = excluded.description;

insert into public.utbms_expense_codes (code, name, description) values
('E101','Copying','Copying charges.'),
('E102','Outside Printing','Outside printing charges.'),
('E103','Word Processing','Word processing charges.'),
('E104','Facsimile','Facsimile charges.'),
('E105','Telephone','Telephone charges.'),
('E106','Online Research','Online research charges.'),
('E107','Delivery Services/Messengers','Delivery and messenger services.'),
('E108','Postage','Postage.'),
('E109','Local Travel','Local travel.'),
('E110','Out-of-Town Travel','Out-of-town travel.'),
('E111','Meals','Meals.'),
('E112','Court Fees','Court fees.'),
('E113','Subpoena Fees','Subpoena fees.'),
('E114','Witness Fees','Witness fees.'),
('E115','Deposition Transcripts','Deposition transcripts.'),
('E116','Trial Transcripts','Trial transcripts.'),
('E117','Trial Exhibits','Trial exhibits.'),
('E118','Litigation Support Vendors','Litigation support vendors.'),
('E119','Experts','Experts.'),
('E120','Private Investigators','Private investigators.'),
('E121','Arbitrators/Mediators','Arbitrators and mediators.'),
('E122','Local Counsel','Local counsel.'),
('E123','Other Professionals','Other professionals.'),
('E124','Other','Other expense.')
on conflict (code) do update set name = excluded.name, description = excluded.description;
